### ISSUE TITLE
Error retrieving information from server

### ISSUE THREAD

**Issue by auduno** [egirault/googleplay-api#16]
Hi, 

I'm trying to do a simple search, "python search.py earth", but get this response:

Title;Package name;Creator;Super Dev;Price;Offer Type;Version Code;Size;Rating;Num Downloads
Traceback (most recent call last):
  File "search.py", line 39, in <module>
    doc = message.doc[0]
  File "C:\Program Files\Python 2.6\lib\site-packages\google\protobuf\internal\containers.py", line 64, in **getitem**
    return self._values[key]
IndexError: list index out of range

Any other action also either fails or return no results.

Looking closer at the message details (with python debugger), it seems this is what is returned from google play:

{displayErrorMessage: "Error retrieving information from server. [DF-DFERH-01]"}

With some searching on the web, it seems this error is not uncommon, but the cause for it is very unclear. Anyone else have any experience with this error?

Thanks,

Audun

**Comment by auduno** [comment]
By the way, this is happening on several computers, both Windows and Linux. And I'm in Norway, if that makes any difference.

**Comment by auduno** [comment]
I generated a new android id with android-checkin, and I no longer get "Error retrieving information from server". However, when trying "python search.py earth" I still get an error "list index out of range". The complete message from google servers is now:

```
payload {
  searchResponse {
    originalQuery: "earth"
    aggregateQuery: false
    relatedSearch {
      searchUrl: "search?q=earth"
      header: "All"
    }
    relatedSearch {
      searchUrl: "search?c=3&q=earth"
      header: "Apps"
      backendId: 3
      current: true
    }
  }
}
```

I suspect it has something to do with the locale that my device id is attached to, but I'm not sure. Does anyone know if there is a way I can set variables in android-checkin when generating device id to fix it?

**Comment by forgetpwd** [comment]
Hi, you may already have answer. just for those people have the similar issues:
1. i got the similar error message at first when enter android_id from settings.db under /data/data/com.android.providers.settings
1. later i refer to this link http://norwied.wordpress.com/2012/08/10/download-android-install-files-apk-from-play-google-com/, particularly step 4,  after enter the correct android_id, now everything works fine.

hope that it helps

**Comment by auduno** [comment]
Ah, a million thanks! 

I'd already tried getting android device-id by punching _#_#8255#_#_, but never managed to get up the Gtalk Service Monitor for some reason. Instead I'd used an android id that seemingly was the wrong one.

Now it all works, thanks!
