### ISSUE TITLE
search.py always returns an error message 

### ISSUE THREAD

**Issue by virtualabs** [egirault/googleplay-api#3]
Seems non-working (again).

$ python search.py "angry birds"
Error: something went wrong. Maybe the nb_res you specified was too big?
$ python search.py "angry birds" 10
Error: something went wrong. Maybe the nb_res you specified was too big?

**Comment by egirault** [comment]
Are you sure the AndroidID you provided in googleplay.py is correct?

**Comment by Fuzion24** [comment]
This has to do with the androidID thing.. you have to make sure it contains letters and is an appropriate length. 
    self.androidId =  "44f1ae6f18171794"
something like the above should work

**Comment by Fuzion24** [comment]
You don't need a valid one to search .. only to download.

**Comment by virtualabs** [comment]
Oh jeez, you guys are right. thx a lot =). I mistyped my androidID.
