### ISSUE TITLE
Bad download size for some apps

### ISSUE THREAD

**Issue by cryptax** [egirault/googleplay-api#34]
Hi!

Looks like the displayed size for some packages is wrong:

Downloading app: com.gameloft.android.ANMP.GloftR3HM with id: xyz
Downloading 857.4MB... Done
Downloading app: com.gameloft.android.ANMP.GloftR2HM with id: xyz
Downloading 467.8MB... Done

The apps above are fortunately not as big as that :) (around 21M)

This is a minor bug.

I suppose that in the code, the size format is corrupt or incorrect:
print "Downloading %s..." % sizeof_fmt(doc.details.appDetails.installationSize),

Regards

**Comment by badrigopalan** [comment]
Unfortunately, the displayed size _IS_ correct. The full size of the app should have the apk, and the expansion (obb) files. The total size is the sum of all three. This code only downloads the main apk, not the expansion files, so the apk size after download is smaller that what the doc.details.appDetails.installationSize is. 

Ideally, the script would download the apk, main and patch obb files.
