### ISSUE TITLE
Optimization for downloading

### ISSUE THREAD

**Issue by wqswlp** [egirault/googleplay-api#4]
This is a question or feature request rather than a bug report.

Current implementation get the downloadURL from a query
 message = self.executeRequestApi2(path, data)  url = message.payload.buyResponse.purchaseStatusResponse.appDeliveryData.downloadUrl

this will hit google play every time when we download a single app.
In the case I use this to enumerate the google play and download free apps one by one, the google server will throttle our searches and block googleplay-api.

Is there a way to craft the downloadURL since we already know the packagename and authtoken and cookie?
My tcpdump shows that the downloadURL has consistent format but different token for each app.

**Comment by egirault** [comment]
Indeed this would be useful. I didnt perform any analysis on the
downloadURL but I guess it is pretty random and unpredictable. But any
help/optimization would be appreciated!

**Comment by strazzere** [comment]
You cannot craft a downloadURL as the token generated in an unpredictable manner with tokens tied to the download.

I'd suggest you instead invest into thinking of a back off strategy along side of some rate limiting.

**Comment by wqswlp** [comment]
Hi Tim

Thanks for replying.
Completely agreed with you, given current google play protocol.

I have a off-topic question,
I send resume to your company through company website, but got no response,
Can you help with that?

David

Date: Mon, 19 Nov 2012 11:19:03 -0800
