### ISSUE TITLE
Retrieve more than 250 results

### ISSUE THREAD

**Issue by ryanhubbell** [egirault/googleplay-api#46]
I know there's a cap of 100 results per search, but after playing around with things for a bit, it seems it only will ever return 250 total results. Is there any way to increase this amount, or does google limit searches to a total of 250 results?

No matter what I put in for a search, it will not return anything if you use an offset of 250.

**Comment by p3r1c0** [comment]
Hi @ryanidev,

I have the same problem. 
How you got increase to 250 the number of results?
I need to obtain more than 100 results.

Could you help me please?
Best regards

**Comment by p3r1c0** [comment]
Hi @ryanidev,
I need your help!
Thanks

**Comment by ryanhubbell** [comment]
It was 2 years ago that I was using the library. I don't use it anymore, and can't remember what I had changed, sorry.
