### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by awasthi-vivek** [egirault/googleplay-api#6]
Hi,

This is a question then a bug. I just noticed that for login we use
https://android.clients.google.com/auth
instead of
https://www.google.com/accounts/ClientLogin
which is used in other projects...

Could you please brief me about the difference between them or point me to some documentation about it.

Many thanks,

**Comment by egirault** [comment]
Hi,

I don't really know, since both are working properly. As far as I remember,
the Google Play APK uses https://android.clients.google.com/auth, so that
is why I used this one.

Cheers,
Emilien

2012/10/25 VivekAwsathi notifications@github.com

**Comment by awasthi-vivek** [comment]
Thank-you very much for your response.

**Comment by strazzere** [comment]
They both appears to be access points for the same API, though like Emilien said - this is what is used on the actual Android clients.
