### ISSUE TITLE
API is dead by now !

### ISSUE THREAD

**Issue by IMAN4K** [egirault/googleplay-api#72]
Important: ClientLogin has been officially deprecated since April 20, 2012 and is now no longer available. Requests to ClientLogin will fail with a HTTP 404 response. We encourage you to migrate to OAuth 2.0 as soon as possible.
Google hint: https://developers.google.com/identity/protocols/AuthForInstalledApps
https://github.com/egirault/googleplay-api/blob/master/googleplay.py#L41

**Comment by nguyenvulong** [comment]
Regarding the ClientLogin, the last time I checked, on Jan as I remember, it still worked, but now it is not working anymore
Do you have any idea why Google left  it last for about 5 years before officially terminating it?

**Comment by IMAN4K** [comment]
@nguyenvulong
Don't know exactly the google strategies AND also don't know why there is no official API from google until 2017 !!
If you know how we should send an API request to google i'm glad to begin

**Comment by nguyenvulong** [comment]
@IMAN4K  
I found this project, which is derived (indirectly) from  egirault's work
Seems like it's working with the new APIs of Google Play Store

See here: https://github.com/yeriomin/YalpStore
