### ISSUE TITLE
get details for excepted platform?

### ISSUE THREAD

**Issue by d954mas** [egirault/googleplay-api#75]
Can i get details only for x86 or arm? For now i get last version code. For example if application have different apk for different platforms i will get details for apk with last version code. But o need version code for excepted platform(for example arm)

**Comment by p3r1c0** [comment]
Hi, @d954mas ,
If you see a branch of this project: 
https://github.com/paolocalciati/googleplay-api
You can see a new call that should obtain the reviews.
I hope it helps you.
Regards.
